import 'package:culcul/i18n/strings.g.dart';

class RankingCategory {
  final String name;
  final int? rid;

  const RankingCategory({required this.name, this.rid});

  String label(Translations t) => switch (name) {
    'all' => t.ranking.categories.all,
    'animation' => t.ranking.categories.animation,
    'bangumi' => t.ranking.categories.bangumi,
    'guochuang' => t.ranking.categories.guochuang,
    'music' => t.ranking.categories.music,
    'dance' => t.ranking.categories.dance,
    'game' => t.ranking.categories.game,
    'knowledge' => t.ranking.categories.knowledge,
    'technology' => t.ranking.categories.technology,
    'sports' => t.ranking.categories.sports,
    'car' => t.ranking.categories.car,
    'life' => t.ranking.categories.life,
    'food' => t.ranking.categories.food,
    'animal' => t.ranking.categories.animal,
    'kichiku' => t.ranking.categories.kichiku,
    'fashion' => t.ranking.categories.fashion,
    'information' => t.ranking.categories.information,
    'entertainment' => t.ranking.categories.entertainment,
    'film' => t.ranking.categories.film,
    'documentary' => t.ranking.categories.documentary,
    'movie' => t.ranking.categories.movie,
    'tv' => t.ranking.categories.tv,
    'tech_digital' => t.ranking.categories.tech_digital,
    'short_play' => t.ranking.categories.short_play,
    'fashion_beauty' => t.ranking.categories.fashion_beauty,
    'sports_fitness' => t.ranking.categories.sports_fitness,
    'vlog' => t.ranking.categories.vlog,
    'painting' => t.ranking.categories.painting,
    'ai' => t.ranking.categories.ai,
    'home' => t.ranking.categories.home,
    'outdoor' => t.ranking.categories.outdoor,
    'fitness' => t.ranking.categories.fitness,
    'craft' => t.ranking.categories.craft,
    'travel' => t.ranking.categories.travel,
    'three_rural' => t.ranking.categories.three_rural,
    'parenting' => t.ranking.categories.parenting,
    'health' => t.ranking.categories.health,
    'emotion' => t.ranking.categories.emotion,
    'life_interest' => t.ranking.categories.life_interest,
    'life_experience' => t.ranking.categories.life_experience,
    _ => name,
  };
}

final rankingCategories = [
  const RankingCategory(name: 'all'),
  const RankingCategory(name: 'animation', rid: 1005),
  const RankingCategory(name: 'game', rid: 1008),
  const RankingCategory(name: 'kichiku', rid: 1007),
  const RankingCategory(name: 'music', rid: 1003),
  const RankingCategory(name: 'dance', rid: 1004),
  const RankingCategory(name: 'film', rid: 1001),
  const RankingCategory(name: 'entertainment', rid: 1002),
  const RankingCategory(name: 'knowledge', rid: 1010),
  const RankingCategory(name: 'tech_digital', rid: 1012),
  const RankingCategory(name: 'information', rid: 1009),
  const RankingCategory(name: 'food', rid: 1020),
  const RankingCategory(name: 'short_play', rid: 1021),
  const RankingCategory(name: 'car', rid: 1013),
  const RankingCategory(name: 'fashion_beauty', rid: 1014),
  const RankingCategory(name: 'sports_fitness', rid: 1018),
  const RankingCategory(name: 'animal', rid: 1024),
  const RankingCategory(name: 'vlog', rid: 1029),
  const RankingCategory(name: 'painting', rid: 1006),
  const RankingCategory(name: 'ai', rid: 1011),
  const RankingCategory(name: 'home', rid: 1015),
  const RankingCategory(name: 'outdoor', rid: 1016),
  const RankingCategory(name: 'fitness', rid: 1017),
  const RankingCategory(name: 'craft', rid: 1019),
  const RankingCategory(name: 'travel', rid: 1022),
  const RankingCategory(name: 'three_rural', rid: 1023),
  const RankingCategory(name: 'parenting', rid: 1025),
  const RankingCategory(name: 'health', rid: 1026),
  const RankingCategory(name: 'emotion', rid: 1027),
  const RankingCategory(name: 'life_interest', rid: 1030),
  const RankingCategory(name: 'life_experience', rid: 1031),
];
